version: '3.8'

services: 
  app:
    build: 
      context: .
    ports: 
      - 3000:3000
    environment: 
      MONGODB_URL: mongodb://mongo:27017
    volumes:
      - .:/usr/src/app
    command: bash -c "npm run build; npm start"
    container_name: "app_container"
  
  mongo:
    image: mongo
    restart: always
    volumes: 
      - mongodb:/data/db
    ports:
      - 27017:27017
    container_name: "db_container"
    
volumes:
  mongodb: